# Generated by Django 4.0.3 on 2022-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date closed'),
        ),
    ]
